
INSERT INTO seguimiento_egresado.seguimiento_fase_1 (seguimiento_id, fase1_participacion, fase1_situacion, fase1_trabajando, fase1_primerempleo, fase1_medios) VALUES
(1, NULL, NULL, NULL, NULL, NULL),
(2, NULL, NULL, NULL, NULL, NULL),
(5, NULL, NULL, NULL, NULL, NULL),
(6, NULL, NULL, NULL, NULL, NULL),
(7, NULL, NULL, NULL, NULL, NULL),
(8, NULL, NULL, NULL, NULL, NULL),
(13, NULL, NULL, NULL, NULL, NULL),
(30, NULL, NULL, NULL, NULL, NULL),
(33, NULL, NULL, NULL, NULL, NULL),
(39, NULL, NULL, NULL, NULL, NULL),
(45, NULL, NULL, NULL, NULL, NULL),
(47, NULL, NULL, NULL, NULL, NULL),
(50, NULL, NULL, NULL, NULL, NULL),
(54, NULL, NULL, NULL, NULL, NULL),
(56, NULL, NULL, NULL, NULL, NULL),
(57, NULL, NULL, NULL, NULL, NULL),
(62, NULL, NULL, NULL, NULL, NULL),
(63, NULL, NULL, NULL, NULL, NULL),
(67, NULL, NULL, NULL, NULL, NULL),
(72, NULL, NULL, NULL, NULL, NULL),
(77, NULL, NULL, NULL, NULL, NULL),
(78, NULL, NULL, NULL, NULL, NULL),
(80, NULL, NULL, NULL, NULL, NULL),
(81, NULL, NULL, NULL, NULL, NULL),
(82, NULL, NULL, NULL, NULL, NULL),
(86, NULL, NULL, NULL, NULL, NULL),
(87, NULL, NULL, NULL, NULL, NULL),
(90, NULL, NULL, NULL, NULL, NULL),
(94, NULL, NULL, NULL, NULL, NULL),
(98, NULL, NULL, NULL, NULL, NULL),
(99, NULL, NULL, NULL, NULL, NULL),
(104, NULL, NULL, NULL, NULL, NULL),
(105, NULL, NULL, NULL, NULL, NULL),
(108, NULL, NULL, NULL, NULL, NULL),
(111, NULL, NULL, NULL, NULL, NULL),
(113, NULL, NULL, NULL, NULL, NULL),
(114, NULL, NULL, NULL, NULL, NULL),
(117, NULL, NULL, NULL, NULL, NULL),
(120, NULL, NULL, NULL, NULL, NULL),
(123, NULL, NULL, NULL, NULL, NULL),
(125, NULL, NULL, NULL, NULL, NULL),
(126, NULL, NULL, NULL, NULL, NULL),
(130, NULL, NULL, NULL, NULL, NULL),
(132, NULL, NULL, NULL, NULL, NULL),
(137, NULL, NULL, NULL, NULL, NULL),
(141, NULL, NULL, NULL, NULL, NULL),
(146, NULL, NULL, NULL, NULL, NULL),
(147, NULL, NULL, NULL, NULL, NULL),
(149, NULL, NULL, NULL, NULL, NULL),
(150, NULL, NULL, NULL, NULL, NULL),
(151, NULL, NULL, NULL, NULL, NULL),
(153, NULL, NULL, NULL, NULL, NULL),
(155, NULL, NULL, NULL, NULL, NULL),
(156, NULL, NULL, NULL, NULL, NULL),
(159, NULL, NULL, NULL, NULL, NULL),
(161, NULL, NULL, NULL, NULL, NULL),
(163, NULL, NULL, NULL, NULL, NULL),
(168, NULL, NULL, NULL, NULL, NULL),
(169, NULL, NULL, NULL, NULL, NULL),
(170, NULL, NULL, NULL, NULL, NULL),
(174, NULL, NULL, NULL, NULL, NULL),
(175, NULL, NULL, NULL, NULL, NULL),
(176, NULL, NULL, NULL, NULL, NULL),
(177, NULL, NULL, NULL, NULL, NULL),
(178, NULL, NULL, NULL, NULL, NULL),
(179, NULL, NULL, NULL, NULL, NULL),
(181, NULL, NULL, NULL, NULL, NULL),
(182, NULL, NULL, NULL, NULL, NULL),
(184, NULL, NULL, NULL, NULL, NULL),
(191, NULL, NULL, NULL, NULL, NULL),
(192, NULL, NULL, NULL, NULL, NULL),
(195, NULL, NULL, NULL, NULL, NULL),
(203, NULL, NULL, NULL, NULL, NULL),
(208, NULL, NULL, NULL, NULL, NULL),
(210, NULL, NULL, NULL, NULL, NULL),
(215, NULL, NULL, NULL, NULL, NULL),
(220, NULL, NULL, NULL, NULL, NULL),
(221, NULL, NULL, NULL, NULL, NULL),
(227, NULL, NULL, NULL, NULL, NULL),
(231, NULL, NULL, NULL, NULL, NULL),
(232, NULL, NULL, NULL, NULL, NULL),
(237, NULL, NULL, NULL, NULL, NULL),
(245, NULL, NULL, NULL, NULL, NULL),
(247, NULL, NULL, NULL, NULL, NULL),
(255, NULL, NULL, NULL, NULL, NULL),
(256, NULL, NULL, NULL, NULL, NULL),
(270, NULL, NULL, NULL, NULL, NULL),
(271, NULL, NULL, NULL, NULL, NULL),
(272, NULL, NULL, NULL, NULL, NULL),
(273, NULL, NULL, NULL, NULL, NULL),
(274, NULL, NULL, NULL, NULL, NULL),
(277, NULL, NULL, NULL, NULL, NULL),
(285, NULL, NULL, NULL, NULL, NULL),
(287, NULL, NULL, NULL, NULL, NULL),
(295, NULL, NULL, NULL, NULL, NULL),
(296, NULL, NULL, NULL, NULL, NULL),
(297, NULL, NULL, NULL, NULL, NULL),
(298, NULL, NULL, NULL, NULL, NULL),
(300, NULL, NULL, NULL, NULL, NULL),
(301, NULL, NULL, NULL, NULL, NULL),
(303, NULL, NULL, NULL, NULL, NULL),
(305, NULL, NULL, NULL, NULL, NULL),
(308, NULL, NULL, NULL, NULL, NULL),
(309, NULL, NULL, NULL, NULL, NULL),
(313, NULL, NULL, NULL, NULL, NULL),
(316, NULL, NULL, NULL, NULL, NULL),
(317, NULL, NULL, NULL, NULL, NULL),
(318, NULL, NULL, NULL, NULL, NULL),
(320, NULL, NULL, NULL, NULL, NULL),
(321, NULL, NULL, NULL, NULL, NULL),
(322, NULL, NULL, NULL, NULL, NULL),
(323, NULL, NULL, NULL, NULL, NULL),
(325, NULL, NULL, NULL, NULL, NULL),
(328, NULL, NULL, NULL, NULL, NULL),
(330, NULL, NULL, NULL, NULL, NULL),
(333, NULL, NULL, NULL, NULL, NULL),
(334, NULL, NULL, NULL, NULL, NULL),
(337, NULL, NULL, NULL, NULL, NULL),
(340, NULL, NULL, NULL, NULL, NULL),
(343, NULL, NULL, NULL, NULL, NULL),
(346, NULL, NULL, NULL, NULL, NULL),
(350, NULL, NULL, NULL, NULL, NULL),
(351, NULL, NULL, NULL, NULL, NULL),
(361, NULL, NULL, NULL, NULL, NULL),
(363, NULL, NULL, NULL, NULL, NULL),
(365, NULL, NULL, NULL, NULL, NULL),
(367, NULL, NULL, NULL, NULL, NULL),
(371, NULL, NULL, NULL, NULL, NULL),
(375, NULL, NULL, NULL, NULL, NULL),
(376, NULL, NULL, NULL, NULL, NULL),
(385, NULL, NULL, NULL, NULL, NULL),
(386, NULL, NULL, NULL, NULL, NULL),
(387, NULL, NULL, NULL, NULL, NULL),
(388, NULL, NULL, NULL, NULL, NULL),
(393, NULL, NULL, NULL, NULL, NULL),
(394, NULL, NULL, NULL, NULL, NULL),
(396, NULL, NULL, NULL, NULL, NULL),
(400, NULL, NULL, NULL, NULL, NULL),
(405, NULL, NULL, NULL, NULL, NULL),
(407, NULL, NULL, NULL, NULL, NULL),
(420, NULL, NULL, NULL, NULL, NULL),
(421, NULL, NULL, NULL, NULL, NULL),
(422, NULL, NULL, NULL, NULL, NULL),
(430, NULL, NULL, NULL, NULL, NULL),
(432, NULL, NULL, NULL, NULL, NULL),
(435, NULL, NULL, NULL, NULL, NULL),
(436, NULL, NULL, NULL, NULL, NULL),
(442, NULL, NULL, NULL, NULL, NULL),
(445, NULL, NULL, NULL, NULL, NULL),
(447, NULL, NULL, NULL, NULL, NULL),
(449, NULL, NULL, NULL, NULL, NULL);

INSERT INTO seguimiento_egresado.seguimiento_fase_2 (seguimiento_id, fase2_satisfaccionestudios, fase2_participacion, fase2_satisfaccionservicio, fase2_planificacion, fase2_empresanombre, fase2_empresaempleadornombre, fase2_empresaempleadorcorreo, fase2_empresaempleadornumero) VALUES
(9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Complejo agroindustrial Beta ', 'Luz flores chavil ', 'lflores@beta.com.pe', NULL),
(23, 'Ni satisfecho ni insatisfecho', 'No', 'Satisfecho', 'No', '-', '-', '-', NULL),
(26, 'Muy satisfecho', 'No', 'Satisfecho', 'No', 'Industrias y representaciones wilcami ', 'Nicolás Reyes ', 'Nicolasrm17@gmail.com', NULL),
(29, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'Innzpira', 'Moisés Fernández Flores', 'mfernandez@easec.eu', NULL),
(37, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(41, 'Satisfecho', 'No', 'Satisfecho', 'Sí', 'CyJ Construcciones', 'Carlos Castilla', 'cyjconstrucciones393@gmail.com', NULL),
(42, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Agrícola Guili ', 'Alex Palomino', ' ', NULL),
(44, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(46, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(51, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'Muy satisfecho', 'Sí', 'Satisfecho', 'No', 'Grupo La Republica Publicaciones ', 'Luis Farfan', 'Luis.farfan@glr.pe', NULL),
(53, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'Dirección Regional Agraria', 'Juan Nicolás Vivanco', 'juannv@gmail.com', NULL),
(55, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(59, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(61, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(65, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(66, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(69, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'IESTP GILDA LILIANA BALLVIAN ROSADO', 'DIRECTOR GENERAL - Dr. LEDGAR SOVERO SOVERO', 'lsovero@institucioneducativa.edu.pe', NULL),
(75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(89, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Complejo agroindustrial Beta', 'Luz flores chavil ', 'lflores@beta.com.pe', NULL),
(92, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Mvl consulting srl', 'Billy', 'kiharasantanamotta@gmail.com', NULL),
(100, 'Satisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'EMAPISCO S.A.', 'Ing Juan del Carmen Mimbela Leon ', 'Juan.mimbela@otass.gob.pe', NULL),
(101, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(102, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Indra Peru ', 'Rodolfo Redondo', 'rjredondo@indracompany.com', NULL),
(109, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Clínica chorrillos ', 'Liliana', 'Cynsb27@gmail.com', NULL),
(110, 'Muy satisfecho', 'Sí', 'Satisfecho', 'No', 'Cafimi', 'Fidel', 'Fidelgroup@gmail.com', NULL),
(115, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(116, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(118, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(121, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(122, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(127, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(131, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(134, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(136, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(138, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(139, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(140, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(143, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(145, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(148, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(152, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(164, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(165, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'ISART GROUP SAC', 'Renato Toce', 'renatotoce@gmail.com', NULL),
(166, 'Satisfecho', 'No', 'Satisfecho', 'No', 'UNIVERSIDAD PRIVADA SAN JUAN BAUTISTA ', 'CELIDE ZUAZO TATAJE', 'celide.zuazo@upsjb.edu.pe', NULL),
(171, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'Rock Drill S.A.C', 'Maricielo Rivera Nuñez', 'enfermeria.ocupacional@rockdrillgroup.com', NULL),
(183, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(186, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Estudio Jurídico Rivera ', 'Nilo Rivera', 'nilorivera@outlook.com', NULL),
(187, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(188, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Inpe ', 'Oscar Janampa paz ', 'hrojass@inpe.com.pe', NULL),
(190, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Estudio Jurídico ', 'ESTUDIO RIVERA', 'nilorivera@outlook.com', NULL),
(193, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(194, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(197, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(199, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(201, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(202, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(204, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(205, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'EMAPE S.A.', 'Herbert Martin Endo Farias', 'hendo@emape.gob.pe', NULL),
(207, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(209, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(211, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(216, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Universidad Continental', 'Percy ', '.', NULL),
(217, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(219, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(222, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ministerio Publico', 'Ricardo Ortiz ', 'rortiz@gmail.com ', NULL),
(223, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'UPSJB', 'Lic. Milagros Montalvo Lamadrid', 'milagros.montalvo@upsjb.edu.pe', NULL),
(224, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(226, 'Muy satisfecho', 'No', 'Satisfecho', 'No', 'Ministerio Público ', 'Wilson Sanchez Socorro', 'Es institucional ', NULL),
(228, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(229, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(233, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(234, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(235, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(236, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(238, 'Muy satisfecho', 'No', 'Satisfecho', 'No', 'HS SECURITY SAC ', 'Rosa María Huamani Segura', 'ggeneral@hssecuritysac.com', NULL),
(239, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ministerio público ', 'Ricardo Ortiz ', 'rortizdn@mpfn.gob.pe', NULL),
(240, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(241, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(246, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Piandi', 'Dr. Galo Camacho ', 'No recuerdo ', NULL),
(252, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Ministerio público ', 'Milagros ', 'Institucional ', NULL),
(254, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Centro Médico de Rehabilitación Integral ', 'Carolina Palmira Muñoz Arotuma ', 'Carola137171@gmail.com', NULL),
(258, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(261, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(262, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(267, 'Satisfecho', 'Sí', 'Muy satisfecho', 'No', 'Policlinico San Juan', 'Marlene Chauca', 'Marlene.chauca@gmail.com', NULL),
(269, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Centro Médico Medina Bushuar Traumatología ', 'Cristian Daniel Medina Bushuar', 'medinabushuarc@gmail.com', NULL),
(283, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(284, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(288, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Banco de crédito del Perú ', 'Viviana Castillo', 'Vivianacastillo@bcp.com.pe', NULL),
(290, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Universidad Privada San Juan Bautista ', 'Evelyn Bardales Guzmán ', 'evelyn.bardales@upsjb.edu.pe', NULL),
(291, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(294, 'Ni satisfecho ni insatisfecho', 'No', 'Satisfecho', 'No', 'ORES FOVIME', 'Jorge de la cruz', 'odiseodlcr@gmail.com', NULL),
(302, 'Satisfecho', 'No', 'Satisfecho', 'No', 'UNIVERSIDAD PRIVADA SAN JUAN BAUTISTA', 'CELIDE ZUAZO TATAJE', 'CELIDE.ZUAZO@UPSJB.EDU.PE', NULL),
(304, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(306, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(307, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Will Travel Peru', 'Roberto Calderón Vargas', 'willtravelperumundo@gmail.com', NULL),
(311, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(312, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(314, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Resonet', 'Santiago', '.', NULL),
(324, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(326, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'EPS EMAPAVIGS SA', 'Ing. Marlon burgos', 'marlon.burgos@otass.gob.pe', NULL),
(327, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(331, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ni una', 'Ni una', 'Ni una', NULL),
(332, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(338, 'Ni satisfecho ni insatisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'Superintendencia Nacional de Fiscalización Laboral - SUNAFIL', 'CARLOS JONATAN LOZANO AVILEZ', '2', NULL),
(344, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Estudio Jurídico Cano & Asociados', 'Jorge Cano Ledesma', 'Canoabogados07@gmail.com', NULL),
(347, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(349, 'Satisfecho', 'No', 'Satisfecho', 'No', '.', '.', '.', NULL),
(352, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(353, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(355, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(356, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(357, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(358, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(359, 'Ni satisfecho ni insatisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'CLINICA DE LOS VASQUEZ ', 'Vladimir Gonzales', 'vgonzales@clinicadelosvasquez.com.pe', NULL),
(360, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(362, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(366, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ninguno ', 'No tengo', 'No tengo ', NULL),
(368, 'Satisfecho', 'No', 'Satisfecho', 'No', 'estudio juridico Juscamaita', 'Dra Ruth', 'ruth2108@hotmail.com', NULL),
(370, 'Satisfecho', 'No', 'Satisfecho', 'No', 'PROGRAMA DE ALIMENTACION ESCOLAR -PAE', 'KEVIN ARNOLD PEDRO RAMON VEGA', 'KRAMON@PAE,GOB,PE', NULL),
(372, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(373, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(374, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(378, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'LOS PORTALES', 'JAIRO TAMAYO LINARES', 'sedanosullcaglider@gmail.com', NULL),
(379, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(380, 'Satisfecho', 'No', 'Satisfecho', 'No', 'GRUPO IVA S.A.C.', 'ESTEFANY VACA', '936080089', NULL),
(381, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(382, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(383, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(384, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ositran ', 'Aimee Valenzuela ', '-', NULL),
(389, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(395, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'Centro Médico Solidario de Comas ', 'Alex Porras ', 'Alexporras@gmail.com', NULL),
(398, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'M&PAZ CENTENO  ', 'Hugo Centeno', 'asdasd', NULL),
(399, 'Satisfecho', 'No', 'Satisfecho', 'No', 'CENTRO DE CONCILIACION SEÑOR DE LA JUSTICIA', 'XXX', 'XXXX', NULL),
(423, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(424, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(426, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(427, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(428, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(431, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(437, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Municipalidad de Cieneguilla ', 'Emilio Chávez Huaringa', 'echavezh@municieneguilla.gob.pe', NULL),
(439, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Marina de Guerra del Peru', 'Reservado', 'Reservado ', NULL),
(440, 'Satisfecho', 'No', 'Satisfecho', 'No', 'IEI nuestro señor de los milagros ', 'Trinidad Villaverde gazo', '.', NULL),
(443, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(444, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(446, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Abril Grupo Inmobiliario ', 'Andrea Namuche', 'snamuche@abril.pe', NULL),
(448, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(450, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Municipalidad de Villa salvador  ', 'Ñxxx', 'Xxxx', NULL),
(451, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(452, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'Kashio', 'Xxxx', 'Xxxxx', NULL),
(453, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Notaría Sierralta Ríos Aníbal ', 'Aníbal sierralta ríos ', 'Administracion@notariasierralta.com', NULL),
(454, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Provias Descentralizado ', 'Lic. Mabel Karina Gamarra Leon', 'mgamarra@proviasdes.gob.pe', NULL);

INSERT INTO seguimiento_egresado.seguimiento_fase_3 (seguimiento_id, fase3_especialidad, fase3_participacion, fase3_educacioncontinua) VALUES
(3, NULL, NULL, NULL),
(4, NULL, NULL, NULL),
(14, NULL, NULL, NULL),
(17, NULL, NULL, NULL),
(19, NULL, NULL, NULL),
(20, NULL, NULL, NULL),
(21, NULL, NULL, NULL),
(22, NULL, NULL, NULL),
(24, NULL, NULL, NULL),
(25, NULL, NULL, NULL),
(27, NULL, NULL, NULL),
(28, NULL, NULL, NULL),
(31, NULL, NULL, NULL),
(36, NULL, NULL, NULL),
(38, NULL, NULL, NULL),
(48, NULL, NULL, NULL),
(49, NULL, NULL, NULL),
(58, NULL, NULL, NULL),
(64, NULL, NULL, NULL),
(68, NULL, NULL, NULL),
(70, NULL, NULL, NULL),
(73, NULL, NULL, NULL),
(74, NULL, NULL, NULL),
(76, NULL, NULL, NULL),
(79, NULL, NULL, NULL),
(83, NULL, NULL, NULL),
(84, NULL, NULL, NULL),
(85, NULL, NULL, NULL),
(88, NULL, NULL, NULL),
(91, NULL, NULL, NULL),
(93, NULL, NULL, NULL),
(95, NULL, NULL, NULL),
(96, NULL, NULL, NULL),
(97, NULL, NULL, NULL),
(103, NULL, NULL, NULL),
(106, NULL, NULL, NULL),
(107, NULL, NULL, NULL),
(112, NULL, NULL, NULL),
(119, NULL, NULL, NULL),
(124, NULL, NULL, NULL),
(128, NULL, NULL, NULL),
(129, NULL, NULL, NULL),
(133, NULL, NULL, NULL),
(135, NULL, NULL, NULL),
(142, NULL, NULL, NULL),
(144, NULL, NULL, NULL),
(154, NULL, NULL, NULL),
(157, NULL, NULL, NULL),
(158, NULL, NULL, NULL),
(160, NULL, NULL, NULL),
(162, NULL, NULL, NULL),
(167, NULL, NULL, NULL),
(172, NULL, NULL, NULL),
(173, NULL, NULL, NULL),
(180, NULL, NULL, NULL),
(185, NULL, NULL, NULL),
(189, NULL, NULL, NULL),
(196, NULL, NULL, NULL),
(198, NULL, NULL, NULL),
(200, NULL, NULL, NULL),
(206, NULL, NULL, NULL),
(212, NULL, NULL, NULL),
(213, NULL, NULL, NULL),
(214, NULL, NULL, NULL),
(218, NULL, NULL, NULL),
(225, NULL, NULL, NULL),
(230, NULL, NULL, NULL),
(242, NULL, NULL, NULL),
(243, NULL, NULL, NULL),
(244, NULL, NULL, NULL),
(248, NULL, NULL, NULL),
(249, NULL, NULL, NULL),
(250, NULL, NULL, NULL),
(251, NULL, NULL, NULL),
(253, NULL, NULL, NULL),
(257, NULL, NULL, NULL),
(259, NULL, NULL, NULL),
(260, NULL, NULL, NULL),
(263, NULL, NULL, NULL),
(264, NULL, NULL, NULL),
(265, NULL, NULL, NULL),
(266, NULL, NULL, NULL),
(268, NULL, NULL, NULL),
(275, NULL, NULL, NULL),
(276, NULL, NULL, NULL),
(279, NULL, NULL, NULL),
(286, NULL, NULL, NULL),
(292, NULL, NULL, NULL),
(293, NULL, NULL, NULL),
(299, NULL, NULL, NULL),
(310, NULL, NULL, NULL),
(335, NULL, NULL, NULL),
(339, NULL, NULL, NULL),
(341, NULL, NULL, NULL),
(342, NULL, NULL, NULL),
(345, NULL, NULL, NULL),
(348, NULL, NULL, NULL),
(354, NULL, NULL, NULL),
(364, NULL, NULL, NULL),
(369, NULL, NULL, NULL),
(377, NULL, NULL, NULL),
(390, NULL, NULL, NULL),
(391, NULL, NULL, NULL),
(392, NULL, NULL, NULL),
(397, NULL, NULL, NULL),
(401, NULL, NULL, NULL),
(402, NULL, NULL, NULL),
(403, NULL, NULL, NULL),
(406, NULL, NULL, NULL),
(408, NULL, NULL, NULL),
(409, NULL, NULL, NULL),
(410, NULL, NULL, NULL),
(411, NULL, NULL, NULL),
(412, NULL, NULL, NULL),
(414, NULL, NULL, NULL),
(415, NULL, NULL, NULL),
(416, NULL, NULL, NULL),
(417, NULL, NULL, NULL),
(418, NULL, NULL, NULL),
(429, NULL, NULL, NULL),
(433, NULL, NULL, NULL),
(434, NULL, NULL, NULL),
(438, NULL, NULL, NULL),
(441, NULL, NULL, NULL);

INSERT INTO seguimiento_egresado.seguimiento_fase_4 (seguimiento_id, fase4_investigacion, fase4_participacion, fase4_resultados, fase4_innovacion, fase4_capacitacion, fase4_formacion) VALUES
(32, 'No', NULL, NULL, NULL, NULL, NULL),
(278, 'No', NULL, NULL, NULL, NULL, NULL),
(280, 'No', NULL, NULL, NULL, NULL, NULL),
(281, 'No', NULL, NULL, NULL, NULL, NULL),
(282, 'No', NULL, NULL, NULL, NULL, NULL),
(289, 'No', NULL, NULL, NULL, NULL, NULL),
(315, 'No', NULL, NULL, NULL, NULL, NULL),
(319, 'No', NULL, NULL, NULL, NULL, NULL),
(329, 'No', NULL, NULL, NULL, NULL, NULL),
(336, 'No', NULL, NULL, NULL, NULL, NULL),
(404, 'No', NULL, NULL, NULL, NULL, NULL),
(413, 'No', NULL, NULL, NULL, NULL, NULL),
(419, 'No', NULL, NULL, NULL, NULL, NULL),
(425, 'No', NULL, NULL, NULL, NULL, NULL);
