INSERT INTO seguimiento_egresado.seguimiento_fase_1 ( seguimiento_id, fase1_participacion, fase1_situacion, fase1_trabajando, fase1_primerempleo, fase1_medios ) VALUES
    (264, 'Nunca', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Más de 2 años', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (265, 'Algunas veces', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (266, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (267, 'Muy rara vez', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (268, 'Nunca', 'Desarrollando mi emprendimiento', 'En ámbito relacionado al área de su formación profesional', 'Entre 1 y 2 años', 'Otros'),
    (269, 'Frecuentemente', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (270, 'Algunas veces', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (271, 'Muy rara vez', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Entre 1 y 2 años', 'Bolsa de trabajo gratuita en internet'),
    (272, 'Algunas veces', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (273, 'Nunca', 'Otro', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (274, 'Algunas veces', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (275, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Más de 2 años', 'Bolsa de trabajo gratuita en internet'),
    (276, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (277, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (278, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (279, 'Nunca', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (280, 'Algunas veces', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (281, 'Nunca', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (282, 'Nunca', 'Otro', 'En ámbito no relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (283, 'Muy rara vez', 'Trabajo formal', 'En ámbito no relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (284, 'Nunca', 'Otro', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (285, 'Nunca', 'Trabajo formal', 'En ámbito no relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Bolsa de trabajo gratuita en internet'),
    (286, 'Nunca', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Bolsa de trabajo gratuita en internet'),
    (287, 'Nunca', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Entre 1 y 2 años', 'Ninguno'),
    (288, 'Algunas veces', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (289, 'Algunas veces', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (290, 'Muy rara vez', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (291, 'Nunca', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (292, 'Muy rara vez', 'Responsable del cuidado familiar', 'En ámbito relacionado al área de su formación profesional', 'Más de 2 años', 'Ninguno'),
    (293, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (294, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (295, 'Nunca', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Entre 1 y 2 años', 'Ninguno'),
    (296, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (297, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (298, 'Muy rara vez', 'Otro', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (299, 'Nunca', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Más de 2 años', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (300, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Ninguno'),
    (301, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (302, 'Frecuentemente', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (303, 'Algunas veces', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Entre 1 y 2 años', 'Otros'),
    (304, 'Muy rara vez', 'Buscando trabajo', 'En ámbito no relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (305, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (306, 'Muy rara vez', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (307, 'Muy rara vez', 'Otro;', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (308, 'Nunca', 'Otro;', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Ninguno'),
    (309, 'Nunca', 'Trabajo formal;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (310, 'Nunca', 'Trabajo formal;', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (311, 'Muy rara vez', 'Trabajo formal;', 'En ámbito no relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (312, 'Algunas veces', 'Trabajo formal;', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Bolsa de trabajo gratuita en internet');
    (313, 'Muy rara vez', 'Buscando trabajo;Otro;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (314, 'Algunas veces', 'Buscando trabajo;Trabajo formal;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (315, 'Algunas veces', 'Estudiando un posgrado;Desarrollando mi emprendimiento;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (316, 'Muy rara vez', 'Buscando trabajo;', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (317, 'Algunas veces', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo de la UPSJB SAC/ convocatorias a su correo institucional'),
    (318, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (319, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (320, 'Algunas veces', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (321, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (322, 'Muy frecuentemente', 'Buscando trabajo', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (323, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (324, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (325, 'Muy rara vez', 'Estudiando un posgrado', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (326, 'Muy rara vez', 'Desarrollando la tesis', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Red de egresados, docentes o conocidos de UPSJB SAC'),
    (327, 'Algunas veces', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (328, 'Muy rara vez', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Bolsa de trabajo de la UPSJB SAC/ convocatorias a su correo institucional'),
    (329, 'Frecuentemente', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Red de egresados, docentes o conocidos de UPSJB SAC'),
    (330, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (331, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (332, 'Nunca', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (333, 'Algunas veces', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (334, 'Muy rara vez', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (335, 'Nunca', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (336, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Red de egresados, docentes o conocidos de UPSJB SAC'),
    (337, 'Algunas veces', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (338, 'Muy rara vez', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (339, 'Frecuentemente', 'Otro', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (340, 'Muy rara vez', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (341, 'Nunca', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (342, 'Algunas veces', 'Responsable del cuidado familiar', 'Dentro del área de su formación profesional', 'Más de 2 años', 'Otros'),
    (343, 'Frecuentemente', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (344, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (345, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (346, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (347, 'Algunas veces', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (348, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Bolsa de trabajo de la UPSJB SAC/ convocatorias a su correo institucional'),
    (349, 'Nunca', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (350, 'Nunca', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (351, 'Muy rara vez', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (352, 'Nunca', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (353, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (354, 'Nunca', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (355, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (356, 'Muy rara vez', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (357, 'Frecuentemente', 'Trabajos informales u ocasionales', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (358, 'Muy rara vez', 'Buscando trabajo', 'En ámbito relacionado al área de su formación profesional', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Ninguno'),
    (359, 'Nunca', 'Otro', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Bolsa de trabajo gratuita en internet'),
    (360, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'LinkedIn'),
    (361, 'Nunca', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (362, 'Muy rara vez', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'LinkedIn'),
    (363, 'Algunas veces', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (364, 'Algunas veces', 'Desarrollando mi emprendimiento', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (365, 'Frecuentemente', 'Otro', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (366, 'Algunas veces', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (367, 'Muy frecuentemente', 'Desarrollando la tesis', 'En ámbito no relacionado al área de su formación profesional', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Otros'),
    (368, 'Muy frecuentemente', 'Desarrollando la tesis', 'En ámbito no relacionado al área de su formación profesional', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Otros'),
    (369, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (370, 'Muy rara vez', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (371, 'Nunca', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'LinkedIn'),
    (372, 'Frecuentemente', 'Responsable del cuidado familiar', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (373, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (374, 'Algunas veces', 'Trabajo formal', 'En ámbito no relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (375, 'Muy rara vez', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (376, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (377, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (378, 'Frecuentemente', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (379, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (380, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (381, 'Nunca', 'Otro', 'En ámbito no relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (382, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (383, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (384, 'Muy rara vez', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (385, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (386, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (387, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (388, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (389, 'Frecuentemente', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (390, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (391, 'Frecuentemente', 'Desarrollando mi emprendimiento', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (392, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (393, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (394, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Entre 1 y 2 años', 'Otros'),
    (395, 'Algunas veces', 'Otro', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'LinkedIn'),
    (396, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (397, 'Nunca', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Red de egresados, docentes o conocidos de UPSJB SAC'),
    (398, 'Muy rara vez', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Entre 1 y 2 años', 'Ninguno'),
    (399, 'Nunca', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (400, 'Muy rara vez', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (401, 'Muy rara vez', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (402, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (403, 'Nunca', 'Otro', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (404, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (405, 'Algunas veces', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (406, 'Muy rara vez', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (407, 'Nunca', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Red de egresados, docentes o conocidos de UPSJB SAC'),
    (408, 'Muy rara vez', 'Buscando trabajo', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (409, 'Nunca', 'Trabajo formal;Desarrollando la tesis;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (410, 'Algunas veces', 'Buscando trabajo;', 'Se encuentra sin trabajo', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Ninguno'),
    (411, 'Muy rara vez', 'Buscando trabajo;', 'En ámbito relacionado al área de su formación profesional', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Otros'),
    (412, 'Frecuentemente', 'Trabajo formal;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (413, 'Algunas veces', 'Estudiando un posgrado;', 'Dentro del área de su formación profesional', 'Más de 2 años', 'Otros'),
    (414, 'Nunca', 'Desarrollando mi emprendimiento;Trabajo formal;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'LinkedIn'),
    (415, 'Muy rara vez', 'Estudiando un posgrado', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (416, 'Nunca', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (417, 'Frecuentemente', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (418, 'Muy frecuentemente', 'Desarrollando mi emprendimiento', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (419, 'Muy rara vez', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (420, 'Algunas veces', 'Desarrollando la tesis', 'Dentro del área de su formación profesional', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (421, 'Nunca', 'Otro', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (422, 'Muy frecuentemente', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (423, 'Frecuentemente', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (424, 'Nunca', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (425, 'Algunas veces', 'Estudiando un posgrado', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (426, 'Muy rara vez', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Entre 1 y 2 años', 'Ninguno'),
    (427, 'Algunas veces', 'Desarrollando la tesis', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'LinkedIn'),
    (428, 'Muy rara vez', 'Desarrollando la tesis;', 'Se encuentra sin trabajo', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Ninguno'),
    (429, 'Muy rara vez', 'Buscando trabajo;', 'Se encuentra sin trabajo', 'Durante los primeros 6 meses luego de culminar los estudios', 'Ninguno'),
    (430, 'Muy rara vez', 'Buscando trabajo;', 'Se encuentra sin trabajo', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Otros'),
    (431, 'Nunca', 'Desarrollando la tesis;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (432, 'Muy rara vez', 'Desarrollando la tesis;Trabajo formal;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (433, 'Algunas veces', 'Desarrollando la tesis;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (434, 'Nunca', 'Desarrollando la tesis;Trabajo formal;Comercio, ventas;Desarrollando mi emprendimiento;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Bolsa de trabajo gratuita en internet'),
    (435, 'Nunca', 'Buscando trabajo;', 'Se encuentra sin trabajo', 'Durante los primeros 7 - 12 meses luego de culminar los estudios', 'Otros'),
    (436, 'Muy rara vez', 'Trabajo formal;', 'En ámbito relacionado al área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Bolsa de trabajo gratuita en internet'),
    (437, 'Algunas veces', 'Trabajo formal;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (438, 'Algunas veces', 'Buscando trabajo;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Otros'),
    (439, 'Muy rara vez', 'Desarrollando la tesis;Trabajo formal;', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'LinkedIn'),
    (440, 'Nunca', 'Trabajo formal;', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'LinkedIn'),
    (441, 'Frecuentemente', 'Buscando trabajo', 'Dentro del área de su formación profesional', 'Durante los primeros 6 meses luego de culminar los estudios', 'Red de egresados, docentes o conocidos de UPSJB SAC'),
    (442, 'Muy rara vez', 'Trabajo formal', 'Dentro del área de su formación profesional', 'Más de 2 años', 'Otros'),
    (443, 'Nunca', 'Buscando trabajo', 'En ámbito no relacionado al área de su formación profesional', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Ninguno'),
    (444, 'Algunas veces', 'Comercio, ventas', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Otros'),
    (445, 'Algunas veces', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (446, 'Frecuentemente', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'LinkedIn'),
    (447, 'Muy rara vez', 'Trabajo formal', 'En ámbito no relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Bolsa de trabajo gratuita en internet'),
    (448, 'Algunas veces', 'Buscando trabajo', 'En ámbito relacionado al área de su formación profesional', 'Entre 1 y 2 años', 'Otros'),
    (449, 'Nunca', 'Trabajo formal', 'En ámbito relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Referencia de contactos durante sus prácticas preprofesionales'),
    (450, 'Nunca', 'Buscando trabajo', 'Se encuentra sin trabajo', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (451, 'Algunas veces', 'Trabajo formal;', 'En ámbito no relacionado al área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (452, 'Nunca', 'Buscando trabajo;', 'Se encuentra sin trabajo', 'Aún no he tenido un empleo vinculado directamente a mi profesión', 'Ninguno'),
    (453, 'Nunca', 'Trabajo formal;', 'Dentro del área de su formación profesional', 'Antes de culminar sus estudios universitarios.', 'Ninguno'),
    (454, 'Muy rara vez', 'Desarrollando la tesis;Trabajo formal;Comercio, ventas;', 'Dentro del área de su formación profesional', 'Más de 2 años', 'Otros');
