INSERT INTO seguimiento_egresado.seguimiento_fase_2 ( seguimiento_id, fase2_satisfaccionestudios, fase2_participacion, fase2_satisfaccionservicio, fase2_planificacion, fase2_empresanombre, fase2_empresaempleadornombre, fase2_empresaempleadorcorreo, fase2_empresaempleadornumero ) VALUES
    (112, 'Satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'MUNICIPALIDAD DISTRITAL DE ASIA', 'POL CHARLI ZAVALA VILLALOBOS', 'pol.zavala.villalobos@gmail.com', NULL),
    (113, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'No', 'Vanguard International SAC', 'Diego Gavidia', 'Diego.gavidia@vanguardfresh.pe', NULL),
    (114, 'Satisfecho', 'Sí', 'Ni satisfecho ni insatisfecho', 'Sí', 'Promart', 'Sommer', 'Jefetalento@promart.com', NULL),
    (115, 'Satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Pdc y municipalidad de Grocio prado', 'Paty pero he y Luis Sarabia', 'Tasaycoluis061@gmail.com', NULL),
    (116, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'No', 'HardsoftSolutions', 'Devora canales galindo', 'info@tmhardsoftsolutions.com', NULL),
    (117, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Melia Hotels Internacional', 'Juan', 'Privado', NULL),
    (118, 'Satisfecho', 'No', 'Muy satisfecho', 'No', 'Cosimec AJ SAC', 'Jimmy Felipe Muñoz Guzman', 'Luizgam22@gmail.com', NULL),
    (119, 'Muy satisfecho', 'No', 'Muy satisfecho', 'Sí', 'Corporación criticó la de chincha sac', 'Néstor Humberto Quispe peña', 'nquispe@fruchincha.com.pe', NULL),
    (120, 'Satisfecho', 'No', 'Satisfecho', 'Sí', 'Arife EIRL', 'Dani Martin Torres Matta', 'Mtorres@arifeperu.con', NULL),
    (121, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'COBRECON S.A.', 'Ing,Edwin Rodriguez', 'edwin.rodriguez@cobrecon.com.pe', NULL),
    (122, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Sin comentarios', 'Sin comentarios', 'Sin comentarios', NULL),
    (123, 'Muy satisfecho', 'Sí', 'Satisfecho', 'Sí', 'Inmobiliaria Valle callango sac', 'Lucas Makabe castro', 'No se da', NULL),
    (124, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'ONPE', 'MANUEL CASAS', 'manuel87cas@gmail.com', NULL),
    (125, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'Universidad Privada San Juan Bautista', 'Ing. Rayza Gómez Olivarez', 'rayza.gomez@upsjb.edu.pe', NULL),
    (126, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Safresco', 'Yanira salas', 'ruth.salas@agricolaandrea.com', NULL),
    (127, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Universidad Privada San Juan Bautista SAC', 'Carlos Chavera', 'carlos.chavera@upsjb.edu.pe', NULL),
    (128, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'White Lion technology', 'Dante', 'djara@whiteliontechnology.com', NULL),
    (129, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'kyndryl - IBM', 'Gerardo Giamportoni', '.', NULL),
    (130, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Universidad Privada San Juan Bautista', 'Carlos Chavera Pacherres', 'Carlos.chavera', NULL),
    (131, 'Ni satisfecho ni insatisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'Almeyda & Asociados abogados', 'Sandro Almeyda López', 'sath1682@gmail.com', NULL),
    (132, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Booster Group', 'Felipe Araya', 'mladrondeguevara@boostergroup.pe', NULL),
    (133, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'MAC Representaciones SAC', 'Claudia Rivadeneira', 'cmrr2506@icloud.com', NULL),
    (134, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Tefiried', 'Maritza Chuquitucto', 'No lo recuerdo', NULL),
    (135, 'Satisfecho', 'No', 'Satisfecho', 'Sí', 'Caja Ica', 'Rosgely', '...', NULL),
    (136, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Dolce&Bella Designs SAC', 'Isabella Arévalo', 'sandmitrijeva.4@gmail.com', NULL),
    (137, 'Satisfecho', 'No', 'Muy satisfecho', 'No', 'UPSJB SAC', 'Ing. Gary Flores', 'GARY.FLORES@UPSJB.EDU.PE', NULL),
    (138, 'Muy insatisfecho', 'No', 'Insatisfecho', 'No', 'Lilith Beauty Lounge', 'Pedro Kohatsu', 'lilithbeautyloungemiraflores@gmail.com', NULL),
    (139, 'Satisfecho', 'No', 'Satisfecho', 'No', 'DRIS/DESARROLLO RURAL SUSTENTABLE', 'EDUARDO RIOS', '.', NULL),
    (140, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Osiptel', 'Tania', '…..', NULL),
    (141, 'Ni satisfecho ni insatisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'Independiente', 'Independiente', 'chesco1708@gmail.com', NULL),
    (142, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Upsjb', 'Dra. Sofía Romero Coz', 'Sofía.romero@upsjb.edu.pe', NULL),
    (143, 'Muy satisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'TAPIZ PERU SAC', 'Luigi Quevedo', 'Contabilidad1@tapizperu.com', NULL),
    (144, 'Satisfecho', 'No', 'Satisfecho', 'No', 'IES PRIVADO SERGIO BERNALES', 'Melissa Alva', 'calidad@isergiobernales.edu.pe', NULL),
    (145, 'Satisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'Policlinico Solidario Comas', 'no me permiten dar esa informacion', 'no lo tengo', NULL),
    (146, 'Satisfecho', 'No', 'Muy satisfecho', 'No', 'Carrión y la empresa Intcomex', 'Pierina y Leonardo Chavez', 'Leonardo.chavez@intcomex.com', NULL),
    (147, 'Satisfecho', 'No', 'Satisfecho', 'No', 'independiente', 'no tengo', 'no existe', NULL),
    (148, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'No', 'No laboro por el momento', 'No laboro por el momento', 'No laboro por el momento', NULL),
    (149, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'RC ingenieros', 'Ricardo calderon', 'rcalderon@rcingenieros.com', NULL),
    (150, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'nnnnn', 'mmmm', 'nnnnnnn', NULL),
    (151, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Indecopi', 'No', 'No', NULL),
    (152, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Complejo agroindustrial Beta', 'Luz flores chavil', 'lflores@beta.com.pe', NULL),
    (153, 'Ni satisfecho ni insatisfecho', 'No', 'Satisfecho', 'No', '-', '-', '-', NULL),
    (154, 'Muy satisfecho', 'No', 'Satisfecho', 'No', 'Industrias y representaciones wilcami', 'Nicolás Reyes', 'Nicolasrm17@gmail.com', NULL),
    (155, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'Innzpira', 'Moisés Fernández Flores', 'mfernandez@easec.eu', NULL),
    (156, 'Satisfecho', 'No', 'Satisfecho', 'Sí', 'CyJ Construcciones', 'Carlos Castilla', 'cyjconstrucciones393@gmail.com', NULL),
    (157, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Agrícola Guili', 'Alex Palomino', NULL, NULL),
    (158, 'Muy satisfecho', 'Sí', 'Satisfecho', 'No', 'Grupo La Republica Publicaciones', 'Luis Farfan', 'Luis.farfan@glr.pe', NULL),
    (159, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'Dirección Regional Agraria', 'Juan Nicolás Vivanco', 'juannv@gmail.com', NULL),
    (160, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'IESTP GILDA LILIANA BALLVIAN ROSADO', 'DIRECTOR GENERAL - Dr. LEDGAR SOVERO SOVERO', 'lsovero@institucioneducativa.edu.pe', NULL),
    -- (161, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Complejo agroindustrial Beta', 'Luz flores chavil', 'lflores@beta.com.pe', NULL),
    (162, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Mvl consulting srl', 'Billy', 'kiharasantanamotta@gmail.com', NULL),
    (163, 'Satisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'EMAPISCO S.A.', 'Ing Juan del Carmen Mimbela Leon', 'Juan.mimbela@otass.gob.pe', NULL),
    (164, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Indra Peru', 'Rodolfo Redondo', 'rjredondo@indracompany.com', NULL),
    (165, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Clínica chorrillos', 'Liliana', 'Cynsb27@gmail.com', NULL),
    (166, 'Muy satisfecho', 'Sí', 'Satisfecho', 'No', 'Cafimi', 'Fidel', 'Fidelgroup@gmail.com', NULL),
    (167, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'ISART GROUP SAC', 'Renato Toce', 'renatotoce@gmail.com', NULL),
    (168, 'Satisfecho', 'No', 'Satisfecho', 'No', 'UNIVERSIDAD PRIVADA SAN JUAN BAUTISTA', 'CELIDE ZUAZO TATAJE', 'celide.zuazo@upsjb.edu.pe', NULL),
    (169, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'Rock Drill S.A.C', 'Maricielo Rivera Nuñez', 'enfermeria.ocupacional@rockdrillgroup.com', NULL),
    -- (170, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Estudio Jurídico Rivera', 'Nilo Rivera', 'nilorivera@outlook.com', NULL),
    (171, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Inpe', 'Oscar Janampa paz', 'hrojass@inpe.com.pe', NULL),
    (172, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Estudio Jurídico', 'ESTUDIO RIVERA', 'nilorivera@outlook.com', NULL),
    (173, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'EMAPE S.A.', 'Herbert Martin Endo Farias', 'hendo@emape.gob.pe', NULL),
    (174, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Universidad Continental', 'Percy', '.', NULL),
    (175, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ministerio Publico', 'Ricardo Ortiz', 'rortiz@gmail.com', NULL),
    (176, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'UPSJB', 'Lic. Milagros Montalvo Lamadrid', 'milagros.montalvo@upsjb.edu.pe', NULL),
    (177, 'Muy satisfecho', 'No', 'Satisfecho', 'No', 'Ministerio Público', 'Wilson Sanchez Socorro', 'Es institucional', NULL),
    (178, 'Muy satisfecho', 'No', 'Satisfecho', 'No', 'HS SECURITY SAC', 'Rosa María Huamani Segura', 'ggeneral@hssecuritysac.com', NULL),
    -- (179, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ministerio público', 'Ricardo Ortiz', 'rortizdn@mpfn.gob.pe', NULL),
    (180, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Piandi', 'Dr. Galo Camacho', 'No recuerdo', NULL),
    (181, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Ministerio público', 'Milagros', 'Institucional', NULL),
    (182, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Centro Médico de Rehabilitación Integral', 'Carolina Palmira Muñoz Arotuma', 'Carola137171@gmail.com', NULL),
    (183, 'Satisfecho', 'Sí', 'Muy satisfecho', 'No', 'Policlinico San Juan', 'Marlene Chauca', 'Marlene.chauca@gmail.com', NULL),
    (184, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Centro Médico Medina Bushuar Traumatología', 'Cristian Daniel Medina Bushuar', 'medinabushuarc@gmail.com', NULL),
    (185, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Banco de crédito del Perú', 'Viviana Castillo', 'Vivianacastillo@bcp.com.pe', NULL),
    (186, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Universidad Privada San Juan Bautista', 'Evelyn Bardales Guzmán', 'evelyn.bardales@upsjb.edu.pe', NULL),
    (187, 'Ni satisfecho ni insatisfecho', 'No', 'Satisfecho', 'No', 'ORES FOVIME', 'Jorge de la cruz', 'odiseodlcr@gmail.com', NULL),
    -- (188, 'Satisfecho', 'No', 'Satisfecho', 'No', 'UNIVERSIDAD PRIVADA SAN JUAN BAUTISTA', 'CELIDE ZUAZO TATAJE', 'CELIDE.ZUAZO@UPSJB.EDU.PE', NULL),
    (189, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Will Travel Peru', 'Roberto Calderón Vargas', 'willtravelperumundo@gmail.com', NULL),
    (190, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Resonet', 'Santiago', '.', NULL),
    (191, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'EPS EMAPAVIGS SA', 'Ing. Marlon burgos', 'marlon.burgos@otass.gob.pe', NULL),
    (192, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ni una', 'Ni una', 'Ni una', NULL),
    (193, 'Ni satisfecho ni insatisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'Superintendencia Nacional de Fiscalización Laboral - SUNAFIL', 'CARLOS JONATAN LOZANO AVILEZ', '2', NULL),
    (194, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Estudio Jurídico Cano & Asociados', 'Jorge Cano Ledesma', 'Canoabogados07@gmail.com', NULL),
    (195, 'Satisfecho', 'No', 'Satisfecho', 'No', '.', '.', '.', NULL),
    (196, 'Ni satisfecho ni insatisfecho', 'No', 'Ni satisfecho ni insatisfecho', 'No', 'CLINICA DE LOS VASQUEZ', 'Vladimir Gonzales', 'vgonzales@clinicadelosvasquez.com.pe', NULL),
    (197, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ninguno', 'No tengo', 'No tengo', NULL),
    (198, 'Satisfecho', 'No', 'Satisfecho', 'No', 'estudio juridico Juscamaita', 'Dra Ruth', 'ruth2108@hotmail.com', NULL),
    (199, 'Satisfecho', 'No', 'Satisfecho', 'No', 'PROGRAMA DE ALIMENTACION ESCOLAR -PAE', 'KEVIN ARNOLD PEDRO RAMON VEGA', 'KRAMON@PAE,GOB,PE', NULL),
    (200, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'LOS PORTALES', 'JAIRO TAMAYO LINARES', 'sedanosullcaglider@gmail.com', NULL),
    (201, 'Satisfecho', 'No', 'Satisfecho', 'No', 'GRUPO IVA S.A.C.', 'ESTEFANY VACA', '936080089', NULL),
    (202, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Ositran', 'Aimee Valenzuela', '-', NULL),
    (203, 'Satisfecho', 'Sí', 'Satisfecho', 'Sí', 'Centro Médico Solidario de Comas', 'Alex Porras', 'Alexporras@gmail.com', NULL),
    (204, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'M&PAZ CENTENO', 'Hugo Centeno', 'asdasd', NULL),
    (205, 'Satisfecho', 'No', 'Satisfecho', 'No', 'CENTRO DE CONCILIACION SEÑOR DE LA JUSTICIA', 'XXX', 'XXXX', NULL),
    (206, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Municipalidad de Cieneguilla', 'Emilio Chávez Huaringa', 'echavezh@municieneguilla.gob.pe', NULL),
    (207, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Marina de Guerra del Peru', 'Reservado', 'Reservado', NULL),
    (208, 'Satisfecho', 'No', 'Satisfecho', 'No', 'IEI nuestro señor de los milagros', 'Trinidad Villaverde gazo', '.', NULL),
    (209, 'Satisfecho', 'No', 'Satisfecho', 'No', 'Abril Grupo Inmobiliario', 'Andrea Namuche', 'snamuche@abril.pe', NULL),
    (210, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Municipalidad de Villa salvador', 'Ñxxx', 'Xxxx', NULL),
    (211, 'Satisfecho', 'Sí', 'Satisfecho', 'No', 'Kashio', 'Xxxx', 'Xxxxx', NULL),
    (212, 'Muy satisfecho', 'Sí', 'Muy satisfecho', 'Sí', 'Notaría Sierralta Ríos Aníbal', 'Aníbal sierralta ríos', 'Administracion@notariasierralta.com', NULL),
    (213, 'Muy satisfecho', 'No', 'Muy satisfecho', 'No', 'Provias Descentralizado', 'Lic. Mabel Karina Gamarra Leon', 'mgamarra@proviasdes.gob.pe', NULL);
