INSERT INTO seguimiento_egresado.seguimiento_fase_3 ( seguimiento_id, fase3_especialidad, fase3_participacion, fase3_educacioncontinua ) VALUES
    (59,  'Maestrías', 'Nunca', 'Cursos de herramientas tecnológicas'),
    (60,  'No cuento con otro grado', 'Muy rara vez', 'Diplomados'),
    (61,  'No cuento con otro grado', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (62,  'No cuento con otro grado', 'Algunas veces', 'Cursos de actualización de la carrera'),
    -- (65,  'No cuento con otro grado', 'Muy rara vez', 'Maestrías / Doctorados'),
    (63,  'No cuento con otro grado', 'Nunca', 'Cursos de gestión'),
    (64,  'No cuento con otro grado', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (65,  'Diplomados', 'Nunca', 'Cursos de actualización de la carrera'),
    -- (69,  'Otros', 'Algunas veces', 'Diplomados'),
    (66,  'Otros', 'Algunas veces', 'Cursos de gestión'),
    (67,  'Otros', 'Muy rara vez', 'Maestrías / Doctorados'),
    (68,  'Otros', 'Nunca', 'Diplomados'),
    -- (73,  'Otros', 'Muy rara vez', 'Diplomados'),
    (69,  'Diplomados', 'Muy rara vez', 'Maestrías / Doctorados'),
    (70,  'No cuento con otro grado', 'Muy rara vez', 'Cursos de herramientas tecnológicas'),
    (71,  'No cuento con otro grado', 'Muy rara vez', 'Maestrías / Doctorados'),
    (72,  'Maestrías', 'Frecuentemente', 'Cursos científicos o de investigación'),
    (73,  'Maestrías', 'Frecuentemente', 'Cursos de gestión'),
    (74,  'No cuento con otro grado', 'Nunca', 'Maestrías / Doctorados'),
    (75,  'Maestrías', 'Algunas veces', 'Maestrías / Doctorados'),
    (76,  'No cuento con otro grado', 'Muy rara vez', 'Maestrías / Doctorados'),
    (77,  'Otros', 'Nunca', 'Cursos de actualización de la carrera'),
    (78,  'Maestrías', 'Algunas veces', 'Maestrías / Doctorados'),
    (79,  'Maestrías', 'Nunca', 'Diplomados'),
    (80,  'Otros', 'Nunca', 'Cursos de actualización de la carrera'),
    (81,  'No cuento con otro grado', 'Nunca', 'Maestrías / Doctorados'),
    (82,  'No cuento con otro grado', 'Algunas veces', 'Maestrías / Doctorados'),
    (83,  'Diplomados', 'Nunca', 'Cursos de herramientas tecnológicas'),
    (84,  'Otros', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (85,  'Otros', 'Nunca', 'Maestrías / Doctorados'),
    (86,  'No cuento con otro grado', 'Muy frecuentemente', 'Cursos de herramientas tecnológicas'),
    (87,  'Otros', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (88,  'Maestrías', 'Muy rara vez', 'Maestrías / Doctorados'),
    (89,  'No cuento con otro grado', 'Muy rara vez', 'Diplomados'),
    (90,  'No cuento con otro grado', 'Muy rara vez', 'Cursos de gestión'),
    (91,  'Otros', 'Muy rara vez', 'Cursos de herramientas tecnológicas'),
    (92,  'No cuento con otro grado', 'Muy rara vez', 'Diplomados'),
    (93,  'Otros', 'Nunca', 'Cursos de actualización de la carrera'),
    (94,  'No cuento con otro grado', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (95, 'Otros', 'Nunca', 'Maestrías / Doctorados'),
    (96, 'Otros', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (97, 'No cuento con otro grado', 'Muy rara vez', 'Diplomados'),
    (98, 'No cuento con otro grado', 'Muy rara vez', 'Cursos de gestión'),
    (99, 'No cuento con otro grado', 'Algunas veces', 'Cursos de actualización de la carrera'),
    (100, 'No cuento con otro grado', 'Muy rara vez', 'Cursos de actualización de la carrera'),
    (101, 'No cuento con otro grado', 'Muy rara vez', 'Diplomados'),
    -- (107, 'Otros', 'Algunas veces', 'Cursos de herramientas tecnológicas'),
    (102, 'Maestrías', 'Algunas veces', 'Maestrías / Doctorados'),
    (103, 'Maestrías', 'Algunas veces', 'Cursos de actualización de la carrera'),
    (104, 'Diplomados', 'Frecuentemente', 'Diplomados'),
    (105, 'No cuento con otro grado', 'Nunca', 'Cursos de actualización de la carrera');
