INSERT INTO seguimiento_egresado.seguimiento_fase_4 ( seguimiento_id, fase4_investigacion, fase4_participacion, fase4_resultados, fase4_innovacion, fase4_capacitacion, fase4_formacion) VALUES (1,  'Sí', NULL, NULL, 'Frecuentemente', NULL, 'Satisfecho'),
    (2,  'Sí', NULL, NULL, 'Muy frecuentemente', NULL, 'Muy satisfecho'),
    (3,  'Sí', NULL, NULL, 'Muy frecuentemente', NULL, 'Muy satisfecho'),
    (4,  'No', NULL, NULL, 'Muy frecuentemente', NULL, 'Muy satisfecho'),
    (5,  'No', NULL, NULL, NULL, NULL, NULL),
    (6,  'No', NULL, NULL, NULL, NULL, NULL),
    (7,  'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (8,  'No', NULL, NULL, NULL, NULL, NULL),
    (9,  'No', NULL, NULL, 'Muy rara vez', NULL, 'Neutro'),
    (10, 'Sí', 'Integrante del equipo.', 'Publicaciones científicas.;Presentaciones o ponencias en eventos académicos.', 'Varias veces al año.', 'Sí, y estoy satisfecho(a).', 'Ni de acuerdo ni en desacuerdo.'),
    -- (11, 'Sí', 'Integrante del equipo.', 'Presentaciones o ponencias en eventos académicos.', 'Permanentemente.', 'Sí, y estoy satisfecho(a).', 'De acuerdo.'),
    (11, 'No', NULL, NULL, NULL, NULL, NULL),
    (12, 'No', NULL, NULL, NULL, NULL, NULL),
    (13, 'No', NULL, NULL, NULL, NULL, NULL),
    (14, 'No', NULL, NULL, NULL, NULL, NULL),
    (15, 'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (16, 'Sí', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (17, 'No', NULL, NULL, NULL, NULL, NULL),
    (18, 'No', NULL, NULL, NULL, NULL, NULL),
    (19, 'Sí', 'Integrante del equipo.;Otro', 'Libros o capítulos de libro.', 'Ocasionalmente.', 'No he participado.', 'En desacuerdo.'),
    (20, 'No', NULL, NULL, 'Nunca', NULL, 'Satisfecho'),
    (21, 'Sí', 'Coordinador(a).', 'Innovaciones implementadas (productos, servicios o procesos).', 'Ocasionalmente.', 'Sí, y estoy muy satisfecho(a).', 'Totalmente de acuerdo.'),
    (22, 'Sí', NULL, NULL, 'Muy rara vez', NULL, 'Satisfecho'),
    (23, 'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    -- (25, 'Sí', NULL, NULL, 'Muy rara vez', NULL, 'Satisfecho'),
    (24, 'No', NULL, NULL, 'Muy rara vez', NULL, 'Satisfecho'),
    (25, 'No', NULL, NULL, NULL, NULL, NULL),
    (26, 'Sí', 'Asistente de investigación.', 'Presentaciones o ponencias en eventos académicos.', 'Varias veces al año.', 'Sí, y estoy muy satisfecho(a).', 'Totalmente de acuerdo.'),
    (27, 'Sí', NULL, NULL, 'Algunas veces', NULL, 'Satisfecho'),
    (28, 'Sí', NULL, NULL, 'Muy rara vez', NULL, 'Muy satisfecho'),
    (29, 'No', NULL, NULL, 'Algunas veces', NULL, 'Poco satisfecho'),
    (30, 'No', NULL, NULL, 'Muy rara vez', NULL, 'Neutro'),
    (31, 'No', NULL, NULL, NULL, NULL, NULL),
    (32, 'No', NULL, NULL, NULL, NULL, NULL),
    (33, 'No', NULL, NULL, NULL, NULL, NULL),
    (34, 'No', NULL, NULL, NULL, NULL, NULL),
    (35, 'No', NULL, NULL, 'Muy rara vez', NULL, 'Satisfecho'),
    (36, 'No', NULL, NULL, 'Muy rara vez', NULL, 'Neutro'),
    (37, 'Sí', NULL, NULL, 'Algunas veces', NULL, 'Satisfecho'),
    (38, 'No', NULL, NULL, NULL, NULL, NULL),
    (39, 'No', NULL, NULL, NULL, NULL, NULL),
    (40, 'Sí', 'Investigador(a) principal o líder del proyecto.', 'Ninguno de los anteriores.', 'Ocasionalmente.', 'No he participado.', 'De acuerdo.'),
    (41, 'No', NULL, NULL, NULL, NULL, NULL),
    (42, 'No', NULL, NULL, 'Frecuentemente', NULL, 'Satisfecho'),
    (43, 'No', NULL, NULL, 'Algunas veces', NULL, 'Satisfecho'),
    (44, 'Sí', NULL, NULL, 'Muy rara vez', NULL, 'Muy satisfecho'),
    (45, 'Sí', NULL, NULL, 'Algunas veces', NULL, 'Muy satisfecho'),
    (46, 'No', NULL, NULL, 'Algunas veces', NULL, 'Satisfecho'),
    (47, 'Sí', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (48, 'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (49, 'Sí', NULL, NULL, 'Muy rara vez', NULL, 'Satisfecho'),
    (50, 'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (51, 'Sí', NULL, NULL, 'Algunas veces', NULL, 'Satisfecho'),
    (52, 'Sí', NULL, NULL, 'Muy rara vez', NULL, 'Neutro'),
    (53, 'No', NULL, NULL, 'Muy rara vez', NULL, 'Neutro'),
    (54, 'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (55, 'No', NULL, NULL, 'Nunca', NULL, 'Neutro'),
    (56, 'No', NULL, NULL, NULL, NULL, NULL),
    (57, 'No', NULL, NULL, NULL, NULL, NULL),
    (58, 'Sí', 'Integrante del equipo.', 'Innovaciones implementadas (productos, servicios o procesos).', 'Nunca.', 'No he participado.', 'De acuerdo.');
